### PR TITLE
Added Author Tag #27

### PR DESCRIPTION
**Pull request by abbytrombley**
As a blog connoisseur I would like to tag a blog author with a keyword to make searching easier.

Given the user is viewing the Author Details menu
When they select the option to add a tag
Then they should be presented with a list of available tags to choose from

Given the user chooses a tag
When they enter the selection and hit enter
Then the relationship between the tag and the author should be saved to the database

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by tylerhamilton888** [comment]
Appears to be working!

**Comment by aw315** [comment]
works great! nice job

**Comment by Iris-Lee4** [comment]
looks good

**Comment by Revvvolution** [comment]
Great!!!

**Pull request merged**
